import { exprToCode, type FieldDecl, type ResourceDecl } from "../ast.js";
import { Writer } from "./util.js";

const TS_TYPE: Record<FieldDecl["type"], string> = { string: "string", number: "number", boolean: "boolean", Date: "Date" };

/**
 * `_orchidery/resources/<Name>.ts`: the record type, its input type, a
 * FormData parser with coercion and defaults, and the field list for
 * building forms. No runtime dependency.
 */
export function emitResourceModule(r: ResourceDecl): string {
  const w = new Writer();
  w.line(`// Generated by Orchidery from resource ${r.name}. Do not edit; edit the resource instead.`);
  w.line();
  w.line(`export interface ${r.name} {`);
  w.indent(() => {
    w.line("id: string;");
    for (const f of r.fields) w.line(`${f.name}${f.optional ? "?" : ""}: ${TS_TYPE[f.type]};`);
  });
  w.line("}");
  w.line();
  w.line(`export type ${r.name}Input = Omit<${r.name}, "id">;`);
  w.line();
  w.line(`export const ${lower(r.name)}Fields = ${JSON.stringify(r.fields.map((f) => ({ name: f.name, type: f.type, optional: f.optional })))} as const;`);
  w.line();
  w.line(`/** Coerce a submitted form into a ${r.name}Input, applying defaults. Throws on a missing required field. */`);
  w.line(`export function parse${r.name}(form: FormData): ${r.name}Input {`);
  w.indent(() => {
    w.line("const raw = (name: string) => { const v = form.get(name); return v === null ? undefined : String(v); };");
    w.line(`const out: Partial<${r.name}Input> = {};`);
    for (const f of r.fields) {
      const def = f.default ? exprToCode(f.default) : undefined;
      w.line("{");
      w.indent(() => {
        w.line(`const v = raw(${JSON.stringify(f.name)});`);
        switch (f.type) {
          case "boolean":
            w.line(`out.${f.name} = v === undefined ? ${def ?? "false"} : v === "on" || v === "true" || v === "1";`);
            break;
          case "number":
            w.line(`if (v === undefined || v === "") ${fallback(f, def)}`);
            w.line(`else { const n = Number(v); if (Number.isNaN(n)) throw new Error("${f.name} must be a number"); out.${f.name} = n; }`);
            break;
          case "Date":
            w.line(`if (v === undefined || v === "") ${fallback(f, def)}`);
            w.line(`else { const d = new Date(v); if (Number.isNaN(d.getTime())) throw new Error("${f.name} must be a date"); out.${f.name} = d; }`);
            break;
          default:
            w.line(`if (v === undefined || v.trim() === "") ${fallback(f, def)}`);
            w.line(`else out.${f.name} = v.trim();`);
        }
      });
      w.line("}");
    }
    w.line(`return out as ${r.name}Input;`);
  });
  w.line("}");
  return w.toString();
}

function fallback(f: FieldDecl, def: string | undefined): string {
  if (def !== undefined) return `out.${f.name} = ${def};`;
  if (f.optional) return `out.${f.name} = undefined;`;
  return `throw new Error(${JSON.stringify(`${f.name} is required`)});`;
}

export function lower(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}
