import type { TokenEntry } from "../ast.js";

const UNITLESS = new Set(["weight", "z", "opacity", "lineHeight", "line", "flex", "order"]);

export function cssVarName(path: string): string {
  return "--" + path.replace(/\./g, "-");
}

export function cssValue(entry: TokenEntry): string {
  if (typeof entry.value === "string") return entry.value;
  const parts = entry.path.split(".");
  return parts.some((p) => UNITLESS.has(p)) ? String(entry.value) : `${entry.value}px`;
}

export function emitTokensCss(entries: TokenEntry[]): string {
  const lines = entries.map((e) => `  ${cssVarName(e.path)}: ${cssValue(e)};`);
  return `/* Generated by Orchidery. Edit the tokens block in your .orchid files instead. */\n:root {\n${lines.join("\n")}\n}\n`;
}

export function emitTokensTs(entries: TokenEntry[]): string {
  const tree: Record<string, unknown> = {};
  for (const e of entries) {
    const parts = e.path.split(".");
    let cur = tree;
    for (const p of parts.slice(0, -1)) {
      cur[p] ??= {};
      cur = cur[p] as Record<string, unknown>;
    }
    cur[parts[parts.length - 1]!] = `var(${cssVarName(e.path)})`;
  }
  const raw: Record<string, string | number> = Object.fromEntries(entries.map((e) => [e.path, e.value]));
  return (
    "// Generated by Orchidery. Edit the tokens block in your .orchid files instead.\n" +
    `export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
    `/** Raw token values, for code that needs numbers rather than CSS variables. */\n` +
    `export const tokenValues = ${JSON.stringify(raw, null, 2)} as const;\n`
  );
}
